[project]
name = "hc_p1me"
version = "1.0.0"
requires-python = ">=3.12"

[tool.ruff]
line-length = 120
target-version = "py312"
extend-exclude = ["testcases", "scripts", "docs"]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["W293", "I001", "E501"]

[tool.pyright]
pythonVersion = "3.12"
typeCheckingMode = "basic"
venvPath = ".."
venv = ".venv"